# SPDX-License-Identifier: GPL-2.0-only

obj-m += snd-hy310-trid-audio-bridge.o

snd-hy310-trid-audio-bridge-y := \
	audio_bridge_core.o \
	audio_bridge_if.o \
	audio_bridge_mem.o \
	audio_bridge_pcm.o
