# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SND_SOC_SUNXI_H713_CODEC) += snd-soc-sunxi-h713-codec.o
obj-$(CONFIG_SND_SOC_SUNXI_H713_CPUDAI) += snd-soc-sunxi-h713-cpudai.o
obj-$(CONFIG_SND_SOC_SUNXI_H713_MACHINE) += snd-soc-sunxi-h713-machine.o
