obj-$(CONFIG_HY310_CPU_COMM) += hy310-cpu-comm.o
hy310-cpu-comm-objs := cpu_comm_dev.o cpu_comm_mem.o cpu_comm_hw.o cpu_comm_proto.o cpu_comm_fifo.o cpu_comm_channel.o cpu_comm_rpc.o
ccflags-y := -DCONFIG_ARM_CPU_COMM
