# SPDX-License-Identifier: GPL-2.0
obj-m += sun50i-h713-av1-driver.o
sun50i-h713-av1-driver-objs := sun50i-h713-av1-core.o \
				 sun50i-h713-av1-hw.o \
				 sun50i-h713-av1-v4l2.o \
				 sun50i-h713-av1-debugfs.o
