# SPDX-License-Identifier: GPL-2.0
obj-m := sunxi-ge2d.o
sunxi-ge2d-y := sunxi_ge2d_core.o \
                sunxi_ge2d_dt.o \
                sunxi_ge2d_panel.o \
                sunxi_ge2d_backlight.o \
                sunxi_ge2d_fbdev.o \
                sunxi_ge2d_svp.o \
                sunxi_ge2d_osd.o \
                sunxi_ge2d_firmware.o \
                sunxi_ge2d_dlpc3435.o

ccflags-y += -I$(src)
